---
name: Spotify Soloist
version: 0.1.1
slug: soloist
description: >-
  Lossless Spotify Connect speaker for Home Assistant, powered by
  Spotify Soloist
url: https://github.com/jgk-iles/hass-spotify-soloist
arch:
  - aarch64
  - amd64
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  api_key: ""
  initial_volume: 50
  cache_size: 500
  auto_update: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  api_key: password
  initial_volume: int(0,100)
  cache_size: int(0,)
  auto_update: bool
  websocket_port: port?
